### ISSUE TITLE
nested list rendering is incorrect

### ISSUE THREAD

**Issue by sslepian** [sirthias/pegdown#123]
Pegdown appears to render nested ordered lists incorrectly, which breaks the list numbering for the child lists.

For the following Markdown

    1. a

        1. a

        2. b

    2. b

        1. a

        2. b

Here's the HTML output by [John Gruber's Markdown test site](http://daringfireball.net/projects/markdown/dingus):

http://jsfiddle.net/u7GJt/

And here's the HTML output of Pegdown:

http://jsfiddle.net/qTDs6/

Pegdown's output is breaking the inner list into two separate \<ol\> tags, which breaks list numbering.

**Comment by TiS** [comment]
I have similar issue

I have following markdown:

    2. XYZ
        1. A

            - XYZ
            - XYZ
            - XYZ

            Lorem ipsum...

        2. B
            - XYZ
            - XYZ
            - XYZ

As you see, GitHUB (and other MarkDown editors I checked) render this as follows:

2. XYZ
    1. A

        - XYZ
        - XYZ
        - XYZ

        Lorem ipsum...
        
    2. B
        - XYZ
        - XYZ
        - XYZ

Unfortunately, this library treats first sub-sub list (and the Lorem Ipsum) as code block. What's more, it restarts list numbering for sub-list (A,B).

**Comment by vsch** [comment]
The list parser had errors in the parsing rules. These showed up for loose sub-items because not all relevant text was collected for recursive parsing of sub-item elements.
