### ISSUE TITLE
code block work error

### ISSUE THREAD

**Issue by yidongnan** [sirthias/pegdown#138]
code block:

    int i=0;
    
    i++;

render result work error
![image](https://cloud.githubusercontent.com/assets/3163314/4056835/397b467c-2dc0-11e4-8ced-f61d942c478e.png)

code block:

    int i=0;
    i++;

render result don't work
![image](https://cloud.githubusercontent.com/assets/3163314/4056858/7e88a2aa-2dc0-11e4-9c02-cd4388717d4e.png)

**Comment by christ66** [comment]
@sirthias I _think_ the issue is the space between the two lines which causes the rendering to not be correct.

**Comment by vsch** [comment]
It looks more like he is trying to create a code block with indents without leaving a blank line between the paragraph and the code block.

It is not an error but a misunderstanding of markdown. 

I think this issue can be closed.

**Comment by sirthias** [comment]
Ok, thanks @vsch!
