### ISSUE TITLE
java.lang.IncompatibleClassChangeError exception, can maven be updated?

### ISSUE THREAD

**Issue by debugging** [sirthias/pegdown#148]
Hi,

I am seeing this when trying to parse some markdown.  I am using scala for this:

```java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class```

I'm using SBT and the version seems a bit old, not like github.  Could someone update the maven repository so this error goes away?

maven has 1.4.2 from december 2013 http://mvnrepository.com/artifact/org.pegdown/pegdown

**Comment by sirthias** [comment]
1.4.2 is the most recent version.
I don't quite understand what exactly you are asking for.

**Comment by debugging** [comment]
Sorry for not being clear.

I was reading an older issue and the suggestion was to update the version of asm (https://github.com/sirthias/pegdown/issues/66).  But since I am using 1.4.2 maybe the issue is something else?

Any suggestions as to why I am getting this error?

Here is what I am doing when I get the IncompatibleClassChangeError:

```
val htmlSerializer:ToHtmlSerializer = null
val processor = new PegDownProcessor(ALL & ~SMARTYPANTS & ~HARDWRAPS) 
val markdown = FileUtils.readAllCharsFromResource(body)
 val astRoot = processor.parseMarkdown(markdown)
val actualHtml = Option(htmlSerializer).getOrElse(new ToHtmlSerializer(new LinkRenderer)).toHtml(astRoot)
```

BTW, I thought it was not the latest version because when I tried adding 
```~ANCHORLINKS```
to the constructor I was getting an error as it couldn't resolve ~ANCHORLINKS so I figured that was in the newer version.

**Comment by mikesname** [comment]
@debugging Perhaps check if your project's dependencies are transitively pulling in asm-3.x somewhere? Pegdown requires asm-4.x since version 1.2, and having them both on the classpath will likely lead to the error you're seeing.

**Comment by debugging** [comment]
@mikesname Yes that seems to be the issue, Google's Guice is using asm 3.1
```
[info]   | +-com.google.inject:guice:3.0
[info]   | | +-aopalliance:aopalliance:1.0
[info]   | | +-javax.inject:javax.inject:1
[info]   | | +-org.sonatype.sisu.inject:cglib:2.2.1-v20090111
[info]   | |   +-asm:asm:3.1
```

What options do I have?

**Comment by mikesname** [comment]
Guice 4.0-beta uses asm 4 if upgrading is a possibility. Alternatively, if you don't use any of the AOP stuff you can exclude `org.sonatype.sisu.inject` `cglib`, like [playframework does](https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L113) (in SBT).

**Comment by debugging** [comment]
I added that to my guice dependancy and still get the same error.

"com.google.inject" % "guice" %
guiceVersion exclude("org.sonatype.sisu.inject", "cglib")

**Comment by debugging** [comment]
Thanks I excluded the cglib and it works fine now.
Much appreciated!
