### ISSUE TITLE
Problem with ASM 5.0 in parboiled

### ISSUE THREAD

**Issue by stavytskyi** [sirthias/pegdown#152]
Parboiled v1.1.6 have problem with using asm 5.0
Parboiled team fixed this problem in version 1.1.7
So when project uses asm 5.0 pegdown is crashed when it's instantiated.
User can resolve this problem with project dependencies.
I think is better to fix this problem in parboiled side as I have checked you should change only dependencies from 1.1.6 to 1.1.7

**Comment by sirthias** [comment]
Just released version 1.5.0 which now depends on parboiled 1.1.7.

**Comment by stavytskyi** [comment]
Thanks. It's great.

**Comment by RobWin** [comment]
The ASM dependency of Parboiled causes issues, if you use Pegdown in a project which requires ASM in a different version. For example: https://github.com/bodiam/markdown-to-asciidoc/issues/24

Is there a possibility to release a Pegdown version which shadows Parboiled and its transitive dependencies?
