### ISSUE TITLE
All Spaces Are Removed and Other Issues

### ISSUE THREAD

**Issue by carc1n0gen** [sirthias/pegdown#156]
I am trying to use pegdown in a project where I write web pages in markdown and they are compiled/cached at runtime.  For some reason in the generated html there are NO spaces/newlines and no tags are being created beyond the first h2 (which isn't closed) and hyperlinks.

[markdown](https://raw.githubusercontent.com/carc1n0gen/posts/master/2014-06-17;Create%20a%20JSON%20Web%20Service%20With%20Flight%20PHP;flight,php,howto.md)

[html](http://pastebin.com/PyLXnEZB)

From what I have observed pegdown doesn't support github style code where you indicate the language, but this shouldn't be the cause for all of the other mess.

**Comment by lawrence-dol** [comment]
This must be a fault in the way you read the file (or preprocess it) before handing it over to PegDown. I do exactly this for my web site and it works perfectly with PegDown.
