### ISSUE TITLE
STRIKETHROUGH also enables ANCHORLINKS

### ISSUE THREAD

**Issue by Kevin-Lee** [sirthias/pegdown#159]
| Pegdown version | JDK Version |
|:-----------------------:|:----------------:|
|1.5.0                     |8                    |

If `STRIKETHROUGH` is set, `ANCHORLINKS` is also enabled.

So the following code enables both `STRIKETHROUGH` and `ANCHORLINKS` although I didn't set `ANCHORLINKS`. I had to enable `DEFINITIONS` (or `FENCED_CODE_BLOCKS`) as well otherwise `STRIKETHROUGH` doesn't work.

```java
new PegDownProcessor(DEFINITIONS | STRIKETHROUGH)
```

**Comment by Kevin-Lee** [comment]
Similarly, using `DEFINITIONS` and `ANCHORLINKS` together enables `STRIKETHROUGH`.
```java
new PegDownProcessor(DEFINITIONS | ANCHORLINKS)
```

**Comment by tcreswick** [comment]
This is part of a bigger issue - see my newly raised issue here: https://github.com/sirthias/pegdown/issues/161

**Comment by Kevin-Lee** [comment]
@tcreswick Nice, you can fix it and pull-request. :smile:

**Comment by tcreswick** [comment]
Have created pull request https://github.com/sirthias/pegdown/pull/162 for this.

**Comment by Kevin-Lee** [comment]
Cool! :+1:

**Comment by sirthias** [comment]
Duplicate of #161.
