### ISSUE TITLE
Code block error.

### ISSUE THREAD

**Issue by xtreme-Aditya-Mishra** [sirthias/pegdown#163]
When having two code blocks with two new lines in each, then it seems to not fence off the second code block.

**for example:**
\`\`\`
this is

a test
\`\`\`
string
\`\`\`
with two

code blocks
\`\`\`

**changes into**

'\<pre>\<code>this is

a test
\</code>\</pre>\<p>string\<br/>\`\`\`\<br/>with two\</p>\<p>code blocks\<br/>\`\`\`\</p>'

**where is doesn't respect the second code block.**

**Comment by vsch** [comment]
A blank line must precede the opening code fence sequence. You need to insert a blank line after the line: `string`.
