### ISSUE TITLE
ANCHORLINKS part of Extensions API?

### ISSUE THREAD

**Issue by stevenemrick** [sirthias/pegdown#166]
Hello
  I'm using jbake 2.4.0 and recently upgraded to pegdown 1.5.0 in my pom file.  Jbake uses pegdown extensions to define things like TABLE, HARDWRAPS, etc.  You can also say just 'ALL'.   What I need is the 'ANCHORLINKS' to work which I thought would happen by upgrading to 1.5.0, but then I noticed ANCHORLINKS does not appear in the [api extensions]
(http://www.decodified.com/pegdown/api/index.html?org/pegdown/Extensions.html)

How can I reference ANCHORLINKS using the Extensions API ?

**Comment by Deraen** [comment]
I'm thinking the documentation you linked is just not updated. It exists in the code: https://github.com/sirthias/pegdown/blob/master/src/main/java/org/pegdown/Extensions.java#L106. 

Though it's currently broken because of #161

**Comment by Deraen** [comment]
This has been fixed in 1.6.0. This can be closed.

**Comment by stevenemrick** [comment]
Excellent - thanks.
