### ISSUE TITLE
Trailing Spaces/Tabs should be allowed after --- or === for Setext headers

### ISSUE THREAD

**Issue by vsch** [sirthias/pegdown#176]
If there are spaces after the last - or = in an Setext header then the header is parsed as a paragraph.

straight from <http://docutils.sourceforge.net/mirror/setext/sermon_1+920315.etx.txt>

This is for the --- or === line

     (a) scan forward for a line that's made up of at least 2 leading
          dash characters (=minimum length; a practical consideration)
          with possible trailing white space (spaces, tabs and other
          defacto invisible [control] characters). If applicable, grep
          all such lines globally using the pattern "^--[-]*[\s\t]*$"

I have a fix and test.

Will post PR with a bunch of other parser compatibility and other source range anomalies. Including #175

**Comment by sirthias** [comment]
Great. Thanks, Vladimir!

**Comment by sirthias** [comment]
Closed by #181.
