### ISSUE TITLE
Reference Rule includes trailing blank lines in AST Node's text range

### ISSUE THREAD

**Issue by vsch** [sirthias/pegdown#177]
Reference rule parses trailing blank lines and includes them as the source range of the node.

Reference should not include any blank lines, even the EOL at the end of the line is not needed since  a reference does not span more than one line. 

Only critical for syntax highlighting. Does not affect conversion to HTML.

I have a fix with a test.

**Comment by vsch** [comment]
The same applies to HTML Block. Also fixed.

**Comment by vsch** [comment]
The same applies to HorizontalRule. Also fixed.

**Comment by sirthias** [comment]
Closed by #181.
