### ISSUE TITLE
Currently Pegdown escapes characters used by extensions that are not enabled.

### ISSUE THREAD

**Issue by vsch** [sirthias/pegdown#179]
Escaping extra characters removes the \ in cases where it is not expected.  For example, turning all extensions off and parsing a sequence \| \~ \: will result in the HTML only containing | ~ :+1: 

The escaped character rule should be based on the currently turned on extensions including the plugins.

Fixed with test for *_`&[]<>!#\\'\".+-(){}:|~ which were all the characters included in the current version.
Any characters returned by the `plugin.getSpecialChars()` will be added to the list of escapable characters.

**Comment by sirthias** [comment]
Closed by #181.
