### ISSUE TITLE
StrongEmphSuperNode not properly parsed after special chars

### ISSUE THREAD

**Issue by martinklepsch** [sirthias/pegdown#196]
There's a testcase here: https://github.com/martinklepsch/pegdown/commit/aa36ef5a779f093b02b8cd9e5cda93c770170782

Somehow parsing `(**this** ...` will not properly turn `this` into a StrongEmphSuperNode.

**Comment by vsch** [comment]
That is correct. Emphasis markers have to be preceded by a blank.

**Comment by martinklepsch** [comment]
Interesting. I didn't know. How does one achieve something like (**this** is bold then? Apparently Github Flavoured Markdown supports it.

**Comment by vsch** [comment]
Yes, GFM has a lot of changes. Some good, some not so much. For example, I recently found out that you can indent nested lists with just one space for second level, and two spaces for the second. 

It is changing an already loose spec for Markdown in areas where it isn't that critical.

**Comment by vsch** [comment]
Forgot to answer your question:

```
(<strong>test</strong>
```

See:

(<strong>test</strong>

**Comment by Deraen** [comment]
As far as I can tell, CommonMark supports this: http://spec.commonmark.org/0.22/#example-355

It looks like the most complete markdown specification.
