### ISSUE TITLE
Github Flavored Markdown Fenced Code Blocks

### ISSUE THREAD

**Issue by AlainODea** [sirthias/pegdown#20]
It would be exceptionally great if the plugin supported Github Flavored Markdown's Fenced Code Blocks as well as the PHP Markdown Extra's approach.

Github Flavored Markdown allows:

``````
```scala
class Example(name: String) {
  val field: Option[Int] = None
}
```
``````

To render as:

``` scala
class Example(name: String) {
  val field: Option[Int] = None
}
```

It would be awesome if pegdown could treat blocks like this the same as:

```
~~~
class Example(name: String) {
  val field: Option[Int] = None
}
~~~
```

and render as:

```
class Example(name: String) {
  val field: Option[Int] = None
}
```

Syntax highlighting is a bigger deal and IMHO better delegated to SyntaxHighlighter on the client-side.

Pegdown is great and thank you for building it :)

**Comment by danizen** [comment]
I'm trying to figure out how best to get my Atlassian Stash/Confluence to highlight github fenced code blocks.   They may say its not them, but pegdown, that needs an enhancement.   I need to know whether to tell them to upgrade pegdown or write their own HTML formatter ;)
