### ISSUE TITLE
Disable standard Markdown rules

### ISSUE THREAD

**Issue by md384** [sirthias/pegdown#218]
Is it possible to disable a rule, e.g. disable reference links? The reason I ask is that I am creating a plugin with various rules that use square brackets (which I don't want to change) which interfere with the reference link rules particularly where I have two adjacent square bracket rules, e.g.

    [A:123][B:456]

where `[A:123]` creates a link for an object `A` with some parameter `123` and similarly for `[B:456]`.

**Comment by vsch** [comment]
@md384, as far as I can tell from the history of issues, yes. 

References are part of standard Markdown so they do not have an extension setting that can be disabled.

**Comment by md384** [comment]
@vsch Ok thanks for your help.
