### ISSUE TITLE
Issues with code blocks in sublists

### ISSUE THREAD

**Issue by TB024155** [sirthias/pegdown#57]
I am having a problem with code blocks which are embedded inside of a list within a list.  when the code block is made, it gets aligned with the overarching list instead of the inner list. I copy and paste the code into a GitHub Flavored Parser, and it works fine. here is the code:

---

## Fenced code blocks inside ordered and unordered lists

1. This is a numbered list.
2. I'm going to include a fenced code block as part of this bullet:

    ```
    Code
    More Code
    ```

3. We can put fenced code blocks inside nested bullets, too.
   1. Like this:

        ```
        printf("Hello, World!");
        ```

   2. The key is to indent your fenced block by **(4 * bullet_indent_level)** spaces.
   3. Also need to put a separating newline above and below the fenced block.

---
the error occurs at the code block under the *Like this* item. When parsed in pegdown,  the code gets aligned with the 3 instead of the 1. also, the code breaks the current list. 
here is the html pegdown produces.

<hr/><h2>Fenced code blocks inside ordered and unordered lists</h2>
<ol>
  <li>This is a numbered list.</li>
  <li><p>I'm going to include a fenced code block as part of this bullet:</p><p><code>
Code
More Code
</code></p></li>
  <li><p>We can put fenced code blocks inside nested bullets, too.</p>
  <ol>
    <li>Like this:</li>
  </ol>
  <pre><code>```
printf(&quot;Hello, World!&quot;);
```
</code></pre>
  <ol>
    <li>The key is to indent your fenced block by <strong>(4 * bullet_indent_level)</strong> spaces.</li>
    <li>Also need to put a separating newline above and below the fenced block.</li>
  </ol></li>
</ol>
<hr/></body>

the test code was retrieved from [here](https://gist.github.com/1155906)
thanks to clintel
my first bug report, so sorry if I messed something up.

**Comment by vsch** [comment]
Pull request with the fix posted. The fix makes pegdown and GitHub results identical.
