### ISSUE TITLE
v1.2.0 causes a java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by gary-rowe** [sirthias/pegdown#66]
Hi - thanks for the great work in putting this project together. I hope this is the right place to bring this to your attention.

I was using v1.2.0 in a project as follows:

```
String markdown = "## Example Markdown\n" +
  "\n" +
  "This is a paragraph\n" +
  "\n" +
  "This is another\n" +
  "\n" +
  "[This is a link](http://example.org)";
PegDownProcessor processor = new PegDownProcessor(2000L);
return processor.markdownToHtml(markdown);
```

and I received the following stacktrace

```
Caused by: ! java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode     has interface org.objectweb.asm.ClassVisitor as super class
! at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
blah java blah
! at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
! at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
! at org.parboiled.Parboiled.createParser(Parboiled.java:54)
! at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:66)
! at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:48)
```

This was on JDK1.6.0_37 on a Mac.

I think a binary incompatibility has been introduced between 1.1.0 and 1.2.0 since regressing to 1.1.0 removed the problem.

**Comment by debugging** [comment]
Hi,

I am seeing this error also:

```java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class```

I'm using SBT and the version seems a bit old, not like github.  Could someone update the maven repository so this error goes away?

maven has 1.4.2 from december 2013 http://mvnrepository.com/artifact/org.pegdown/pegdown

**Comment by ravikiranj** [comment]
What version of pegdown, parboiled-core and parboiled-java is compatbile with ASM 3.3.1 ?

**Comment by mikesname** [comment]
As sirthias says 1.2 and up require ASM 4.x, so try [1.1.0](https://github.com/sirthias/pegdown/tree/1.1.0). As you can see in the pom that uses parboiled 1.0.2.

**Comment by RoyTran** [comment]
Thanks DaveShiel, your ideas save my life :)
