### ISSUE TITLE
Invalid nested list rendering 

### ISSUE THREAD

**Issue by kofalt** [sirthias/pegdown#99]
In a nested mixed-type list, numbered lists do not render correctly, and indentation is missing.
Screenshot of the problem (expected vs actual):

![lists](https://f.cloud.github.com/assets/265071/872689/0717e62e-f868-11e2-8896-3c690152a7c4.png)

The example input:

```
1. Numbered item 1
 * Sub-list
1. Numbered item 2
 * Sub-list
1. Numbered item 3
 * Sub-list
```

Results in the following output:

``` html
<ol>
    <li>Numbered item 1</li>
</ol>
<ul>
    <li>Sub-list</li>
</ul>
<ol>
    <li>Numbered item 2</li>
</ol>
<ul>
    <li>Sub-list</li>
</ul>
<ol>
    <li>Numbered item 3</li>
</ol>
<ul>
    <li>Sub-list</li>
</ul></div>
```

Compare with expected output (using Github as an example):

``` html
<ol>
    <li>Numbered item 1
        <ul>
            <li>Sub-list</li>
        </ul>
    </li>
    <li>Numbered item 2
        <ul>
            <li>Sub-list</li>
        </ul>
    </li>
    <li>Numbered item 3
        <ul>
            <li>Sub-list</li>
        </ul>
    </li>
</ol>
```

In both HTML cases I changed whitespace indentation to be consistent for comparison.
Note that changing the input's sub-list indentation from spaces to tabs works.

Originally reported as a bug in Atlassian Stash: https://jira.atlassian.com/browse/STASH-3702

**Comment by stavytskyi** [comment]
I agree with @michaelmior. I think Github markdown spec is more frequently used as [!default markdown](https://daringfireball.net/projects/markdown/).

**Comment by jirutka** [comment]
The original Markdown “spec” from John Gruber is very ambiguous and incomplete, almost unusable for implementing a Markdown parser. The best Markdown spec we have is [CommonMark](http://commonmark.org/).

**Comment by michaelmior** [comment]
Yeah, I think CommonMark compatibility seems like a good goal. Although I am still [somewhat skeptical](https://xkcd.com/927/).

**Comment by kofalt** [comment]
I'd hesitate to consign their efforts to XCKD ignominy; after I gave the CommonMark spec a read, I'm convinced that their output is high quality. In my opinion they've done a great job of massaging MD's original intent and the [fractal insanity of incompatibility](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+top%0A+-+indented+one%0A++-+indented+two%0A+++-+indented+three%0A++++-+indented+four%0A+++++-+indented+five%0A) pretty well. YMMV.

Which part of the fractal pegdown wants to represent is left as an exercise for the maintainer; the main reason I opened this ticket was an inability to get a repository's readme to simultaneously render on stash + github. I would support any movement towards CommonMark, as vendor lock-in is rarely a desirable result.
